# Generated by Django 5.2.6 on 2025-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_options_remove_comment_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
