# Generated by Django 5.2.6 on 2025-10-14 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movie_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='api.rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='movies/illustrations/', verbose_name="Image d'illustration"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/', verbose_name='Affiche'),
        ),
    ]
