# Generated by Django 5.2.6 on 2025-10-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.OneToOneField(null=True, blank=True, to='api.rating', on_delete=models.SET_NULL),
        ),
    ]